version: "3"

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1111
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./postgres:/var/lib/postgresql/data"
      - './sql_updates:/docker-entrypoint-initdb.d'


  app:
    build: .
    volumes:
      - .:/Python
    ports:
    - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
